# 服务注册方的模板配置
server:
  port: 1201
spring:
  application:
    name: template-service
eureka:
  client:
    serviceUrl:
#      defaultZone: http://127.0.0.1:1111/eureka/,http://127.0.0.1:1112/eureka/,http://127.0.0.1:1113/eureka/
      defaultZone: http://127.0.0.1:1111/eureka/