#redis
#数据库索引

server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3307/springcloud?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&serverTimezone=GMT
    username: root
    password: root
    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver

  #redis
  redis:
    database: 0
    host: 127.0.0.1:6379
    password: redis
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.oauth.sys.persist.model  # 注意：对应实体类的路径


#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging.level.org: info
logging.level.com.oauth.sys.persist.mapper: debug
